---
title: "FL50_4way_overlap"
author: "Alice MacQueen"
date: "1/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(switchgrassGWAS)
library(cowplot)
library(viridis)
```

## 


```{r}
mash <- readRDS("~/Github/pvdiv-phenology-gxe/analysis/FL50/Strong_Effects29475SNPs.rds")
```

```{r}
df <- get_significant_results(m=mash) %>%
  enframe(name = "SNP")
df1 <- switchgrassGWAS:::get_marker_df(mash)
df1 <- df1 %>%
  mutate(log10bf = switchgrassGWAS:::get_log10bf(m=mash),
         sigcond = switchgrassGWAS:::get_n_significant_conditions(mash)
         )
switchgrassGWAS:::get_log10bf(m=mash)
switchgrassGWAS::mash_plot_effects(m=mash, i = 26711)

df1 %>%
  filter(log10bf > 5)

panela <- df1 %>%
  filter(grepl("Chr09K_5", Marker) & value > 26500) %>%
  separate(Marker, into = c("Chr", "_", "Position"), sep = c(6,7), remove = FALSE) %>%
  mutate(Position = as.numeric(Position)) %>%
  ggplot(aes(x=Position, y = log10bf)) +
  geom_point(aes(color = sigcond)) +
  scale_color_viridis(option = "B") # 26711
save_plot(filename = "Chr09K_FL50_mash_result_zoom.png", plot = last_plot(), base_asp = 1.5)

p3 <- plot_grid(panela, panelb$ggobject, rel_widths = c(2,1))
save_plot(filename = "Chr09K_FL50_mash_result_zoom_2panel.png", plot = p3, base_asp = 3)
```
#Chr05N
```{r}
panela <- df1 %>%
  filter(grepl("Chr05N_1", Marker) & value > 15717) %>%
  separate(Marker, into = c("Chr", "_", "Position"), sep = c(6,7), remove = FALSE) %>%
  mutate(Position = as.numeric(Position)) %>%
  ggplot(aes(x=Position, y = log10bf)) +
  geom_point(aes(color = sigcond)) +
  scale_color_viridis(option = "B", end = 0.9) 
panelb <- switchgrassGWAS::mash_plot_effects(m=mash, i = 15864)
panelb$ggobject 
p3 <- plot_grid(panela, panelb$ggobject, rel_widths = c(2,1))
save_plot(filename = "Chr05N_FL50_mash_result_zoom.png", plot = p3, base_asp = 3)

```
Chr05N_15045423	15847	4.688166	8	  affects flowering at the 3 major sites
Chr05N_15048576	15849	4.101891	8	
Chr05N_15951722	15863	4.048425	7	  affects flowering at KBSM & CLMB
Chr05N_16084715	15864	4.226715	8	  affects flowering at the 3 major sites


```{r}
panela <- df1 %>%
  filter(grepl("Chr04K_1", Marker) & value > 11158) %>%
  separate(Marker, into = c("Chr", "_", "Position"), sep = c(6,7), remove = FALSE) %>%
  mutate(Position = as.numeric(Position)) %>%
  ggplot(aes(x=Position, y = log10bf)) +
  geom_point(aes(color = sigcond)) +
  scale_color_viridis(option = "B", end = 0.9) 
panelb <- switchgrassGWAS::mash_plot_effects(m=mash, i = 11493)
panelb$ggobject 
p3 <- plot_grid(panela, panelb$ggobject, rel_widths = c(2,1))
save_plot(filename = "Chr04K_FL50_mash_result_zoom.png", plot = p3, base_asp = 3)
df1 %>%
  filter(grepl("Chr04K_1", Marker) & value > 11158 & log10bf > 4)
```
Chr04K_14442056	11332	4.954623	7	
Chr04K_14919129	11382	4.263826	8	
Chr04K_14920267	11384	4.655388	8	
Chr04K_14955235	11388	4.693233	7	
Chr04K_16627327	11460	4.240948	7	
Chr04K_16687695	11493	4.405048	7	
Chr04K_18870690	11610	5.308748	6	
