---
title: "QTL_interval_plotting"
author: "Alice MacQueen"
date: "1/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(qtl)
library(qtl2)
library(qtl2convert)
library(tidyverse)
```

#

```{r prep QTL_Eff df}
###QTL Effect plot
###load the original cross and reduce the markers from 4700 to 1185
load('../phenology-fourway/5-QTLmappingForAlice/sexAveraged.cross.rda', verbose = T)
map  =  lapply(pull.map(cross), function(x) x[1,])
# reduced_markers  =  unlist(
#   lapply(
#     reduce_markers(
#       lapply(pull.map(cross), function(x)
#         x[1,]), min_distance = 1), names))
#
# mars2drop  =  markernames(cross)[!markernames(cross) %in% reduced_markers]
# cross  =  drop.markers(cross, mars2drop)
cross = calc.genoprob(cross, step=1, error.prob = 1e-3,map.function = "kosambi",stepwidth = "max")
######### Converting probalibity from qtl1 to qtl2
probs  =  probs_qtl_to_qtl2(cross)$probs
##calculate the kinship matrix for single site
kinship_loco_Single = calc_kinship(probs,use_allele_probs = F,type = "loco")

###extract the genotype ID from the original cross file, so we can align the phenology file with genotype ID
ID <- data.frame(ID=cross$pheno$id)
ID <- ID %>% mutate_at(vars('ID'), list(as.character)) %>% mutate_at(vars('ID'), list(as.numeric))

######get the phenotype at each site
phenology = read.csv('../phenology-fourway/5-QTLmappingForAlice/FL50_phenotypes_Alice.csv', header = TRUE)
colnames(phenology)[1:2] = c('ID','Covariate')
str(phenology) ###make sure your phenology traits are numeric, if not, change them into numeric
phenos <- phenology %>% mutate_at(vars('ID'), list(as.character)) %>%
  mutate_at(vars('ID'), list(as.numeric))%>% group_by(Covariate,ID ) %>%
  summarize_all(mean, na.rm=T) %>% ungroup()%>% as.data.frame()
```

```{r setup QTL effects for all traits}
###QTL effect for each trait
EffectMatrix = vector('list', length=0)
t=0
for (envi in unique(phenos$Covariate)){
    t=t+1
    pheno = phenos %>% filter(Covariate==envi) %>% dplyr::select(-Covariate) %>%
      select(ID, FL50) %>% right_join(ID) %>%  column_to_rownames('ID') %>% as.matrix()

    ##ran effect scan for each chromosome
    eff_out = vector('list',length = 0)
    se_out = vector('list',length = 0)
    add_contrasts=cbind(mu=c(1,1,1,1), add1=c(-1, 1, -1, 1),add2=c(-1, -1, 1, 1), dom=c(-1, 1, 1, -1))

    z = 0
    for (chr in chrnames(cross)){
      print(c(chr, envi,t))
      z= z+1
      eff = scan1coef(probs[,chr],pheno,kinship = kinship_loco_Single[chr], se=T, contrasts = add_contrasts)
      se = attr(eff, 'SE')
      eff_out[[z]] =  eff %>% as.data.frame() %>% rownames_to_column('MARKER')
      se_out[[z]] =  se %>% as.data.frame() %>% rownames_to_column('MARKER')
    }
    eff_out = bind_rows(eff_out)
    se_out = bind_rows(se_out)

    se_out2 = se_out %>% dplyr::select(-mu) %>% gather('CROSS','SE',-MARKER)
    eff_out2 = eff_out %>% dplyr::select(-mu) %>% gather('CROSS','EFF',-MARKER) %>% mutate(SE=se_out2$SE, Covariate=envi)

    EffectMatrix[[t]] = eff_out2
  }

EffectMatrix2 = bind_rows(EffectMatrix)

###unlist nmap and merge with Effect file
nmap = data.frame(pos = unlist(map))
nnmap = nmap %>% rownames_to_column('MARKER') %>% rowwise() %>%
  mutate(chr = str_sub(MARKER, 1,2), MARKER=str_sub(MARKER, 4,nchar(MARKER)))%>%
  ungroup() %>% mutate(pos=round(pos,4))

flank_marker_full = read.csv('../phenology-fourway/5-QTLmappingForAlice/QTLsWithFlankMarkers_FL50_phenotypes_Alice_7_SITES_Full_model.csv')
flank_marker_full = flank_marker_full %>% mutate_at(vars(chr),list(as.character))

for (i in 1:nrow(flank_marker_full)){
  tmp = nnmap %>% filter(chr==flank_marker_full$chr[i] & pos==round(flank_marker_full$pos[i],4))
  flank_marker_full$MARKER[i] = tmp$MARKER
}

QTL_full_model = flank_marker_full %>% dplyr::rename(trait=lodcolumn)



```

```{r ggplots of QTL effects}
QTLdf <- QTL_full_model %>% left_join(EffectMatrix2)%>%
  mutate(CROSS = str_replace(CROSS,'add2','C x D')) %>%
  mutate(CROSS = str_replace(CROSS,'add1','A x B')) %>%
  mutate(Garden = case_when(Covariate == "BRKG" ~ "SD",
                            Covariate == "CLMB" ~ "MO",
                            Covariate == "KBSM" ~ "MI",
                            Covariate == "KING" ~ "TX1",
                            Covariate == "LINC" ~ "NE",
                            Covariate == "PKLE" ~ "TX2",
                            Covariate == "STIL" ~ "OK",
                            TRUE ~ "Other"),
         Cross = case_when(CROSS == "A x B" ~ "AP13 x DAC",
                           CROSS == "C x D" ~ "VS16 x WBC",
                           CROSS == "dom" ~ "Dominance",
                           TRUE ~ "Other")) %>%
  separate(MARKER, into = c("Chr", "Pos"), sep = "_", convert = TRUE, 
           remove = FALSE) %>%
  mutate(Pos_plot = paste0(Chr, "\n", round(Pos, 1), " Mb"))

QTLdf$Covariate = factor(QTLdf$Covariate, levels=c('KING','PKLE','STIL','CLMB',
                                                       'LINC','KBSM','BRKG'))
QTLdf$Garden = factor(QTLdf$Garden, levels = c("TX1", "TX2", "OK", "MO", 
                                                   "NE", "MI", "SD"))

QTLdf %>% 
  filter(Cross != "Dominance") %>% # trait == 'FL50' &
  ggplot(aes(x = Garden, y = EFF, group = Cross)) +
  geom_point(size = 2) + facet_grid(Cross + trait ~ Pos_plot) +
  geom_hline(yintercept = 0, linetype=2) + 
  geom_errorbar(aes(ymin=EFF-SE, ymax=EFF+SE), size=0.6, width=0.5) +
  xlab("") +
  ylab('QTL Effect') + 
  coord_flip() + 
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        text=element_text(size=12, face="bold"),
        axis.title=element_text(size=12,face="bold"),
        axis.text.x = element_text(size = 10, angle = 45, hjust = 1, vjust = 1))
# shared QTL for more than one trait differ in LOD score, but not meaningfully in effect patterns across gardens. Useful to know.

QTLplot <- QTLdf %>%
  arrange(desc(lod)) %>%
  group_by(Chr, Pos, Garden, Cross) %>%
  slice(1) %>% 
  filter(Cross != "Dominance") # trait == 'FL50' &

QTLplot$Pos_plot <- factor(QTLplot$Pos_plot, levels = c("Chr02K\n8.6 Mb",
                                                        "Chr02K\n64.4 Mb",
                                                        "Chr02N\n19.5 Mb",
                                                        "Chr02N\n58 Mb",
                                                        "Chr02N\n60.3 Mb",
                                                        "Chr02N\n60.9 Mb",
                                                        "Chr02N\n69.4 Mb",
                                                        "Chr03K\n18.6 Mb",
                                                        "Chr04K\n4.7 Mb",
                                                        "Chr04K\n11.8 Mb",
                                                        "Chr05N\n2.3 Mb",
                                                        "Chr05N\n3.2 Mb",
                                                        "Chr05N\n3.4 Mb",
                                                        "Chr05N\n45.9 Mb",
                                                        "Chr05N\n59.9 Mb",
                                                        "Chr05N\n64.9 Mb",
                                                        "Chr05N\n65.3 Mb",
                                                        "Chr07K\n37 Mb",
                                                        "Chr07N\n45.2 Mb",
                                                        "Chr08N\n6.8 Mb",
                                                        "Chr08N\n16.5 Mb",
                                                        "Chr09K\n16.3 Mb",
                                                        "Chr09N\n15.7 Mb"))
#levels(as.factor(QTLplot$Pos_plot))  

QTLplot %>%
  ggplot(aes(x = Garden, y = EFF, group = Cross)) +
  geom_col(size = 1, aes(fill = trait)) + 
  facet_grid(Cross ~ Pos_plot) +
  geom_hline(yintercept = 0, linetype=2) + 
  geom_errorbar(aes(ymin=EFF-SE, ymax=EFF+SE, color = trait), size=0.6, width=0.5) +
  xlab("") + scale_y_continuous(limits = c(-4.25, 6.5), breaks = c(-3, 0, 3)) +
  ylab('QTL Effect') + 
  coord_flip() + 
  switchgrassGWAS::theme_oeco + 
  scale_color_manual(values = c("#CC0066", "#FFCC00", "#006600", "#6600FF")) +
  scale_fill_manual(values = c("#CC0066", "#FFCC00", "#006600", "#6600FF")) +
  theme(legend.position = "top",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        text = element_text(size = 10, face="bold"),
        strip.text = element_text(size = 10, face="bold"),
        axis.title = element_text(size = 10,face="bold"),
        axis.text.x = element_text(size = 10, angle = 45, hjust = 1, vjust = 1),
        )# +
    #scale_y_continuous(expand = c(0.2, 0.2)) 
save_plot(filename = "../manuscript/plots/Figure_4_QTL_effects_by_trait.png", base_height = 4.5, base_width = 13.5, plot = last_plot())

QTLdf %>%
  filter(trait == 'CGDD_12C') 
QTLdf %>% 
  filter(trait == 'dyln_fl50')
QTLdf %>% 
  filter(trait == 'dyln_change_sec') 


```

I could combine this with some plots pulled from the mash object using `mash_plot_effects` to do a side-by-side comparison for the paper. That would go well maybe with the Figure 4 I started today, although of course I can't think of a good way to validate this statistically any more than I did in the other script. 
```{r}
library(switchgrassGWAS)
mash_plot_effects()
```

