---
title: "4-QTLinterval and plotting"
author: "Alice MacQueen"
date: "2/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(qtl)
library(qtl2)
library(plyr)
library(tidyverse)
library(qtl2convert)
library(cowplot)
```


setwd("~/Github/pvdiv-phenology-gxe/phenology-fourway/5-QTLmappingForAlice/")

```{r}
workingdir <- "~/Github/pvdiv-phenology-gxe/phenology-fourway/5-QTLmappingForAlice/"
load(file.path(workingdir, 'cross_reduced_marker_FL50_phenotypes_Alice_7_SITES.RData'))
load(file.path(workingdir, 'scan1Results_FL50_phenotypes_Alice_7_SITES.RData'))

map  =  lapply(pull.map(cross), function(x) x[1,])
###get the threshold value for each model and output the QTL intervals
threshold_full = summary(s1permfull,alpha = 0.05)
threshold_reduced = summary(s1permreduced,alpha = 0.05)
```

```{r}
###  g x e
gxe = s1full - s1reduced
gxe_perm = threshold_full - threshold_reduced ###or gxe_perm = summary(gxe, alpha=0.05)

###get the peak for full model and gxe model
peaks_full = find_peaks(s1full, map, threshold = threshold_full, drop = 1.5, peakdrop = 5)
peaks_gxe = find_peaks(gxe, map, threshold = gxe_perm, drop = 1.5)

flank_marker_full = peaks_full %>% mutate(flank_lo = find_marker(map, chr, ci_lo), flank_hi=find_marker(map, chr, ci_hi))
# write.csv(flank_marker_full,'QTLsWithFlankMarkers_FL50_phenotypes_Alice_7_SITES_Full_model.csv') ###change the name you want

flank_marker_gxe = peaks_gxe %>% mutate(flank_lo = find_marker(map, chr, ci_lo), flank_hi=find_marker(map, chr, ci_hi))
# write.csv(flank_marker_gxe,'QTLsWithFlankMarkers_FL50_phenotypes_Alice_7_SITES_gxe_model.csv')

###########
```

    flowering_cumulative_rainfall_7d    blue            1
    flowering_daylength_change_s_2d     pink            4  
    flowering                           purple          5  
    
    greenup_daylength_14d               green           2
    greenup_daylength_change_s_1d       yellow          3
    greenup                             grey            6
    greenup_temp_ave_1d                 darkorange      7

```{r}
threshold_df <- threshold_full %>% 
  as_tibble(rownames = "Threshold") %>%
  pivot_longer(GR50:crain_7d, names_to = "Phenotype", values_to = "LOD") %>%
  mutate(Phe = case_when(Phenotype %in% c("GR50", "tave_1d", "dyln_14d_prior", "dyln_change_sec") ~ "greenup",
                         Phenotype %in% c("FL50", "dyln_change_sec_2d_prior", "crain_7d") ~ "flowering", 
                         TRUE ~ NA_character_)) 

s1full %>%
  as_tibble(rownames = "Marker") %>%
  pivot_longer(GR50:crain_7d, names_to = "Phenotype", values_to = "LOD") %>%
  mutate(Phe = case_when(Phenotype %in% c("GR50", "tave_1d", "dyln_14d_prior", "dyln_change_sec") ~ "greenup",
                         Phenotype %in% c("FL50", "dyln_change_sec_2d_prior", "crain_7d") ~ "flowering", 
                         TRUE ~ NA_character_)) %>% 
  separate(Marker, into = c("Chr", "Pos"), sep = "_", remove = FALSE, convert = TRUE) %>%
  filter(!grepl("loc", Chr)) %>%
  ggplot(aes(x = Pos, y = LOD)) + 
  geom_line(aes(color = Phenotype)) +
  geom_hline(data = threshold_df, aes(yintercept = LOD, color = Phenotype, linetype = Phenotype)) +
  facet_grid(Phe~Chr, scales = "free_x") +
  switchgrassGWAS::theme_oeco + 
  scale_color_manual(values = c("#000099", "#006600", "#FFCC00", "#CC0066", "#6600FF", "grey", "darkorange", "#000666")) + 
  scale_linetype_manual(values = c(4,4,4,4,4,4,4)) +
  theme(legend.position = "top",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        text = element_text(size = 10, face="bold"),
        strip.text = element_text(size = 10, face="bold"),
        axis.title = element_text(size = 10,face="bold"),
        axis.text.x = element_text(size = 10, angle = 45, hjust = 1, vjust = 1),
        ) + 
  xlab("Position (Mb)") + ylab("LOD score") +
  scale_x_continuous(breaks = c(0, 20, 40, 60, 80))

save_plot(filename = "../manuscript/revision2/Figure_4_QTL_by_lod_score.svg", base_height = 5, base_width = 13.5, plot = last_plot())
```

# Rug plot of mash hits
```{r}
m_gulf_gr_hyp <- readRDS("~/Github/pvdiv-phenology-gxe/analysis/mash/Gulf/Strong_Effects_19000_SNPs_GR50_Gulf_Uhyp.rds")
m_gulf_fl_hyp <- readRDS("~/Github/pvdiv-phenology-gxe/analysis/mash/Gulf/Strong_Effects_19000_SNPs_FL50_Gulf_Uhyp.rds")


m_midw_gr_hyp <- readRDS("~/Github/pvdiv-phenology-gxe/analysis/mash/Midwest/Strong_Effects_24000_SNPs_GR50_Midwest_Uhyp.rds")
m_midw_fl_hyp <- readRDS("~/Github/pvdiv-phenology-gxe/analysis/mash/Midwest/Strong_Effects_33000_SNPs_FL50_Midwest_Uhyp.rds")

m_gam_gr_hyp <- readRDS("~/Github/pvdiv-phenology-gxe/analysis/mash/Gulf_and_Midwest/Strong_Effects_19000_SNPs_GR50_Gulf_and_Midwest_Uhyp.rds")
m_gam_fl_hyp <- readRDS("~/Github/pvdiv-phenology-gxe/analysis/mash/Gulf_and_Midwest/Strong_Effects_19000_SNPs_FL50_Gulf_and_Midwest_Uhyp.rds")
```

```{r}
get_post_weights <- function(m){
  log10bf_df <- switchgrassGWAS:::get_log10bf(m = m) %>%
      as.data.frame() %>%
      rownames_to_column(var = "value") %>%
      dplyr::mutate(value = as.integer(.data$value)) %>%
      as_tibble() %>%
      left_join(switchgrassGWAS:::get_marker_df(m = m), by = "value") %>%
      dplyr::rename(log10BayesFactor = .data$V1) %>%
      dplyr::select(-.data$value)
  
  pw_df <- as_tibble(m$posterior_weights)
  pw_df <- switchgrassGWAS:::get_marker_df(m = m) %>%
    bind_cols(pw_df)
  
  ggman_df <- pw_df %>%
    #left_join(m_meta) %>%
    tidyr::separate(.data$Marker, into = c("Chr", "Pos"), remove = FALSE, sep = "_",
             extra = "merge", convert = TRUE) %>%
    left_join(log10bf_df, by = "Marker") %>%
    dplyr::arrange(.data$Chr, .data$Pos) 
  return(ggman_df)
}

pw_gg <- get_post_weights(m_gulf_gr_hyp)
pw_gf <- get_post_weights(m_gulf_fl_hyp) %>%
  mutate(Subpop = "Gulf")

pw_mg <- get_post_weights(m_midw_gr_hyp)
pw_mf <- get_post_weights(m_midw_fl_hyp) %>%
  mutate(Subpop = "Midwest")

pw_gamg <- get_post_weights(m_gam_gr_hyp)
pw_gamf <- get_post_weights(m_gam_fl_hyp) %>%
  mutate(Subpop = "Both")
```

```{r}
test_rug1 <- pw_gf %>%
  filter(log10BayesFactor > 2) %>% 
  mutate(Pos = Pos/1000000, 
         LOD = -0.5)
test_rug2 <- pw_gamf %>%
  filter(log10BayesFactor > 2) %>% 
  mutate(Pos = Pos/1000000, 
         LOD = -0.5)
test_rug3 <- pw_mf %>%
  filter(log10BayesFactor > 2) %>% 
  mutate(Pos = Pos/1000000, 
         LOD = -0.5)
test_rug <- pw_gf %>%
  full_join(pw_gamf) %>%
  full_join(pw_mf) %>%
  filter(log10BayesFactor > 2) %>% 
  mutate(Pos = Pos/1000000, 
         LOD = -0.5)

test_rug4 <- pw_gg %>%
  filter(log10BayesFactor > 2) %>% 
  mutate(Pos = Pos/1000000, 
         LOD = -0.5)
test_rug5 <- pw_gamg %>%
  filter(log10BayesFactor > 2) %>% 
  mutate(Pos = Pos/1000000, 
         LOD = -0.5)
test_rug6 <- pw_mg %>%
  filter(log10BayesFactor > 2) %>% 
  mutate(Pos = Pos/1000000, 
         LOD = -0.5)
```


```{r}
s1full %>%
  as_tibble(rownames = "Marker") %>%
  pivot_longer(GR50:crain_7d, names_to = "Phenotype", values_to = "LOD") %>%
  filter(Phenotype %in% c("FL50", "dyln_change_sec_2d_prior", "crain_7d")) %>% 
  separate(Marker, into = c("Chr", "Pos"), sep = "_", remove = FALSE, convert = TRUE) %>%
  filter(!grepl("loc", Chr)) %>%
  ggplot(aes(x = Pos, y = LOD)) + 
  geom_line(aes(color = Phenotype)) +
  geom_rug(data = test_rug2, sides = "t", alpha = 0.1) + 
  geom_rug(data = test_rug1, sides = "b", alpha = 0.2) + 
  geom_rug(data = test_rug3, outside = TRUE, sides = "b", alpha = 0.2) + 
  geom_hline(data = filter(threshold_df, 
                           Phenotype %in% c("FL50", "dyln_change_sec_2d_prior", "crain_7d")),
             aes(yintercept = LOD, color = Phenotype, linetype = Phenotype)) +
  facet_wrap(~Chr, nrow = 1, scales = "free_x") +
  switchgrassGWAS::theme_oeco + 
  scale_color_manual(values = c("#000099", "#CC0066", "darkgrey", "#000666")) + 
  scale_linetype_manual(values = c(4,4,4,4,4)) +
  theme(legend.position = "top",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        text = element_text(size = 10, face="bold"),
        strip.text = element_text(size = 10, face="bold"),
        axis.title = element_text(size = 10,face="bold"),
        axis.text.x = element_text(size = 10, angle = 45, hjust = 1, vjust = 1),
        ) + 
  xlab("Position (Mb)") + ylab("LOD score") +
  scale_x_continuous(breaks = c(0, 20, 40, 60, 80)) + 
  coord_cartesian(clip = "off")
save_plot(filename = "../manuscript/revision2/Figure_4_FL50_QTL_by_lod_score_w_rugs.svg", base_height = 3, base_width = 13.5, plot = last_plot())

s1full %>%
  as_tibble(rownames = "Marker") %>%
  pivot_longer(GR50:crain_7d, names_to = "Phenotype", values_to = "LOD") %>%
  filter(Phenotype %in% c("GR50", "tave_1d", "dyln_14d_prior", "dyln_change_sec")) %>% 
  separate(Marker, into = c("Chr", "Pos"), sep = "_", remove = FALSE, convert = TRUE) %>%
  filter(!grepl("loc", Chr)) %>%
  ggplot(aes(x = Pos, y = LOD)) + 
  geom_line(aes(color = Phenotype)) +
  geom_rug(data = test_rug5, sides = "t", alpha = 0.1) + 
  geom_rug(data = test_rug4, sides = "b", alpha = 0.2) + 
  geom_rug(data = test_rug6, outside = TRUE, sides = "b", alpha = 0.2) + 
  geom_hline(data = filter(threshold_df, 
                           Phenotype %in% c("GR50", "tave_1d", "dyln_14d_prior", 
                                            "dyln_change_sec")), 
             aes(yintercept = LOD, color = Phenotype, linetype = Phenotype)) +
  facet_wrap(~Chr, nrow = 1, scales = "free_x") +
  switchgrassGWAS::theme_oeco + 
  scale_color_manual(values = c("#006600", "#FFCC00",  "grey", "darkorange", "#000666")) + 
  scale_linetype_manual(values = c(4,4,4,4,4,4)) +
  theme(legend.position = "top",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        text = element_text(size = 10, face="bold"),
        strip.text = element_text(size = 10, face="bold"),
        axis.title = element_text(size = 10,face="bold"),
        axis.text.x = element_text(size = 10, angle = 45, hjust = 1, vjust = 1),
        ) + 
  xlab("Position (Mb)") + ylab("LOD score") +
  scale_x_continuous(breaks = c(0, 20, 40, 60, 80)) + 
  coord_cartesian(clip = "off")
save_plot(filename = "../manuscript/revision2/Figure_4_GR50_QTL_by_lod_score_w_rugs.svg", base_height = 3, base_width = 13.5, plot = last_plot())
```



Li's additional code
```{r}
###########
png('../2-figures/FL50_7_SITES_LOD_FL50_phenotypes_Alice_7_SITES.png', width = 800)
plot(s1full, map, lodcolumn=2, col="slateblue", ylim=c(0,56))
plot(s1full,map, lodcolumn=3, col="violetred", add=T)
plot(s1full,map, lodcolumn=4, col="darkgreen", add=T)
plot(s1full,map, lodcolumn=5, col="yellow", add=T)
abline(h=threshold_full[2],lty=2,lwd=3,col=c("slateblue"))
abline(h=threshold_full[3],lty=2,lwd=3,col=c("violetred"))
abline(h=threshold_full[4],lty=2,lwd=3,col=c("darkgreen"))
abline(h=threshold_full[5],lty=2,lwd=3,col=c("yellow"))

legend("topleft", lwd=2, col=c("slateblue", "violetred","darkgreen","yellow"), colnames(s1full)[c(2,3,4,5)], bg="gray90")
dev.off()


flank_marker_full = flank_marker_full %>% mutate(GXE= ifelse(pos %in% flank_marker_gxe$pos, 'Y','N'))%>%
  mutate(ChrNo = str_extract(chr, '[1-9]'))%>% mutate_at(vars(ChrNo),as.numeric) %>%
  mutate(Dist = case_when(
    str_detect(chr,'K') ~ (ChrNo*2-1),
    str_detect(chr,'N') ~ ChrNo*2
  ))
# ###6. plot QTL on genetic map
# load('sexAveraged.cross.rda')
png('../2-figures/QTLs_FL50_phenotypes_Alice_7_SITES.png',width = 900)
cols  =  c("violetred","yellow","darkgreen","slateblue") ###add your colors depending on how many traits you have
library(qtlTools)
with(flank_marker_full, segmentsOnMap(cross, phe = lodcolumn, chr = chr,
                                      l = ci_lo, h = ci_hi,
                                      peaklod = lod, peakcM = pos,
                                      showPeaks = TRUE,
                                      chrBuffer = c(0.15,0.1),
                                      tick.width=0.05, lwd="byLod",
                                      col = cols,
                                      leg.inset=.57, legendCex=1,
                                      legendPosition="topleft")
)
#mtext('QTL_7_SITES',side = 3)

for (i in 1:nrow(flank_marker_full)){
    if (flank_marker_full$GXE[i]=='Y')
    text(x=(flank_marker_full$Dist[i]+0.4), y=(flank_marker_full$ci_lo[i]),'*',col = 'red',cex = 1.5)
  }

dev.off()

```


