---
title: "GRM_fourway"
author: "Alice MacQueen"
date: "4/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rlang)
```

## 

```{r}
# paste0(rep(c(1:9),each = 2), rep(c("K", "N"), 9))

# str(cross$geno$`2N`$data)

geno_df <- cross$geno[[1]]$data

for(i in 2:18){
geno_df <- geno_df %>%
  cbind(cross$geno[[i]]$data)
}

# geno_df[1:20,1000:1005]
# length(which(!is.na(geno_df)))
# 50666/6170584 # less than 1% missing data, but it majorly fucks up the kinship matrix.

geno_df2 <- geno_df %>%
  as_tibble() %>%
  mutate_if(is.numeric, list(~ifelse(is.na(.), sample(1:4, 1), .))) # replace NA's with a random value from 1 to 4.

snps <- as.matrix(geno_df2)
# snps[1:20,1000:1005]
```

# GAPIT's method, for comparison purposes
```{r}
`GAPIT.kinship.VanRaden` <-
function(snps,hasInbred=TRUE) {
# Object: To calculate the kinship matrix using the method of VanRaden (2009, J. Dairy Sci. 91:4414???C4423)
# Authors: Zhwiu Zhang
# Last update: August 15, 2011 
############################################################################################## 

print("Calculating kinship with VanRaden method...")

#snps=hm$GD 
nSNP=ncol(snps)
nInd=nrow(snps)
n=nInd

snpMean= apply(snps,2,mean)
snps=snps-snpMean
print("Getting X'X...")
K=tcrossprod((snps), (snps))

print("Adjusting...")
#Extract diagonals
i =1:n
j=(i-1)*n
index=i+j
d=K[index]
DL=min(d)
DU=max(d)
floor=min(K)

K=(K-floor)/(DL-floor)
MD=(DU-floor)/(DL-floor)

#Handler of diagonals over 2
#print("MD")
#print(MD)
#print(K[1:5,1:5])

if(is.na(K[1,1])) stop ("GAPIT says: Missing data is not allowed for numerical genotype data")
if(MD>2)K[index]=K[index]/(MD-1)+1

#Handler of inbred
if(MD<2 & hasInbred) K=2*K/((DU-floor)/(DL-floor))

print("Calculating kinship with VanRaden method: done")

return(K)
}
```

```{r}
K[1:10,1:5]
library(switchgrassGWAS)

mash_plot_pairwise_sharing(corrmatrix = K[1:30,1:30])

write_rds(K, path = "~/Github/pvdiv-phenology-gxe/data/Kinship_van_Raden_5250g_fourway_cross.rds")
```

