---
title: "Mash analysis FL50 and GDD"
author: "Alice MacQueen"
date: "6/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(bigsnpr)
library(switchgrassGWAS)
# need these three for the last code chunk only: visualizing mash results
library(GGally)
library(cowplot)
library(viridis)
```

# Run bigsnp2mashr

Need to do this on the server, that's where I have saved these GWAS_datatables.

Midwest subpop:
CGDD_12C, FL50 x3

```{r}
trim_name <- function(x){
    for(i in seq_along(x)){
  if((str_sub(x[i], start = -1) %in% c("_")))
  { x[i] <- str_sub(x[i], end = -2) }
    }
  return(x)
}

path <- file.path("~", "Github", "pvdiv-phenology-gxe", "analysis", 
                       "gwas", "GDD")

inputfiles <- read_delim(file.path("~", "Github", "pvdiv-phenology-gxe", 
                                   "analysis", "gwas", "inputkinship.txt"), 
                         delim = " ", col_names = "SNPfiles") 
# Midwest & Gulf, Midwest, Gulf, Atlantic, Midwest & Atlantic, Gulf & Atlantic


# Midwest
snp <- snp_attach(inputfiles$SNPfiles[2])
gwas_rds <- pvdiv_results_in_folder(path = path, 
                                    pattern = paste0("GWAS_datatable_",
                                                     "(KBSM|PKLE|CLMB)", ".+",
                                                     "(CGDD_12C|FL50)", 
                                                     ".+",
                                                     "\\d+g_8.8M"))

site_phe <- trim_name(str_sub(gwas_rds, start = 16, end = -41))
numSNPs <- ceiling((1000000 / length(site_phe)^2)/1000)*1000

midwest_mashin <- 
  pvdiv_bigsnp2mashr(path = path, snp = snp,
                    gwas_rds = gwas_rds, phenotypes = site_phe, 
                    numSNPs = numSNPs, scale = TRUE, suffix = "midwest", 
                    saveoutput = TRUE)
# Gulf [3]
snp <- snp_attach(inputfiles$SNPfiles[3])
gwas_rds <- pvdiv_results_in_folder(path = path, 
                                    pattern = paste0("GWAS_datatable_", ".+",
                                                     "(CGDD_12C|FL50)", 
                                                     ".+",
                                                     "\\d+g_10.3M"))

site_phe <- trim_name(str_sub(gwas_rds, start = 16, end = -42))
numSNPs <- ceiling((1000000 / length(site_phe)^2)/1000)*1000

midwest_mashin <- 
  pvdiv_bigsnp2mashr(path = path, snp = snp,
                    gwas_rds = gwas_rds, phenotypes = site_phe, 
                    numSNPs = numSNPs, scale = TRUE, suffix = "gulf", 
                    saveoutput = TRUE)

# Midwest_Gulf [1]
snp <- snp_attach(inputfiles$SNPfiles[1])
gwas_rds <- pvdiv_results_in_folder(path = path, 
                                    pattern = paste0("GWAS_datatable_", ".+",
                                                     "(CGDD_12C|FL50)", 
                                                     ".+",
                                                     "\\d+g_12.1M"))

site_phe <- trim_name(str_sub(gwas_rds, start = 16, end = -42))
numSNPs <- ceiling((1000000 / length(site_phe)^2)/1000)*1000

midwest_mashin <- 
  pvdiv_bigsnp2mashr(path = path, snp = snp,
                    gwas_rds = gwas_rds, phenotypes = site_phe, 
                    numSNPs = numSNPs, scale = TRUE, suffix = "midwest_gulf", 
                    saveoutput = TRUE)

# Atlantic [4]
snp <- snp_attach(inputfiles$SNPfiles[4])
gwas_rds <- pvdiv_results_in_folder(path = path, 
                                    pattern = paste0("GWAS_datatable_",
                                                     "(KBSM|PKLE|CLMB|LINC|TMPL)", 
                                                     ".+", "(CGDD_12C|FL50)", 
                                                     ".+", "\\d+g_10.6M"))
# drop BRKG for the Atlantic subpopulation because it had obvious population structure.

site_phe <- trim_name(str_sub(gwas_rds, start = 16, end = -42))
numSNPs <- ceiling((1000000 / length(site_phe)^2)/1000)*1000

atlantic_mashin <- 
  pvdiv_bigsnp2mashr(path = path, snp = snp,
                    gwas_rds = gwas_rds, phenotypes = site_phe, 
                    numSNPs = numSNPs, scale = TRUE, suffix = "atlantic", 
                    saveoutput = TRUE)

# other things to try... CRAIN... etc.

```

# mash runs
```{r}
path <- file.path("~", "Github", "pvdiv-phenology-gxe", "analysis", 
                       "gwas", "GDD")
phe_suffix <- c("midwest", "gulf", "midwest_gulf", "atlantic")
numSNPs <- c(28000, 10000, 4000, 10000)

m_out <- list()
for(i in 2){
  m_out[[i]] <- mash_standard_run(path = path, numSNPs = numSNPs[i], 
                                  suffix = phe_suffix[i], saveoutput = TRUE)
}
```

```{r}

path <- file.path("~", "Github", "pvdiv-phenology-gxe", "analysis", 
                       "gwas", "GDD")
phe_suffix <- c("midwest", "gulf", "midwest_gulf", "atlantic")
numSNPs <- c(28000, 10000, 4000, 10000)

i = 4
m <- readRDS(file.path(path, paste0("Strong_Effects", numSNPs[i], "SNPs_", 
                                    phe_suffix[i], ".rds")))
U_ed <- readRDS(file.path(path, paste0("Mash_data_driven_covariances_",
                                       numSNPs[i], "_", phe_suffix[i], ".rds")))

mash_plot_manhattan_by_condition(m)
mash_plot_sig_by_condition(m)
mash_plot_pairwise_sharing(m)
mash_plot_effects(m, n = 1)
mash_plot_effects(m, n = 2)

get_significant_results(m)[1:10]
barplot(switchgrassGWAS:::get_estimated_pi(m))

ggcorr(data = NULL, cor_matrix = m$fitted_g$Ulist$`Stand_BhatCLMB_CGDD_12C-mean`)
#ggcorr(data = NULL, cor_matrix = m$fitted_g$Ulist$ED_PCA_2)
thing <- U_ed$ED_PCA_1
ggcorr(data = NULL, cor_matrix = thing, limits = c(min(thing)-.1, max(thing)+.1))

```

Midwest mostly follows covariance matrix ED_PCA_1 and 3.
Gulf ED_PCA_2, 4, and 9.
Midwest_Gulf ED_PCA_1 through 4. 

Atlantic hardly any significant effects for GDD/FL50. 10. 2N, 5K, 5N, 7K, 9K, 9N.
ED_PCA_1.

Try CRAIN and other stuff? FL50 & GDD alone? Hmm.


```{r}
install_github("alice-macqueen/switchgrassGWAS")
```

