---
title: "Phenotypes_best_lambda_GC"
author: "Alice MacQueen"
date: "2/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## 

```{r}
lambdadf <- read_csv("~/Github/pvdiv-phenology-gxe/analysis/Lambda_GC_BRKG_to_OVTN_FL1.csv")
```

```{r}
df <- lambdadf %>% t(.)

df %>% as_tibble(rownames = "Phenotype") %>%
  filter(!(Phenotype %in% c("NumPCs", "LATITUDE", "LONGITUDE", "ELEVATION"))) %>%
  separate(Phenotype, into = c("SITE", "_", "PHE"), sep = c(4,5)) %>%
  dplyr::select(-"_") %>%
  arrange(PHE, SITE) %>%
  filter(PHE != "DEAD_2018") %>%
  rename(V0 = V1, V1 = V2, V2 = V3, V3 = V4, V4 = V5, V5 = V6, V6 = V7)
```
One/two site: 
PKLE leaf k = 4
KING CHLR k = 3
KING SPAD k = 3
RUST k = 3 or k = 2 for PKLE?
KING/TMPL DAM k = 3 

Tensite k = 4:
EM1 k = 4
EM50 k = 4
FL1 k = 4 (OVTN issue but it should be dropped anyway)
FL50 k = 4 (KING k=5...)
HT_PAN_EOS k = 4
T_EM_FL k = 4 (esp for LINC KBSM)
T_GR_EM k = 4
T_GR_FL k = 4

TC_EOS_2018 k = 2 (or possibly k = 4, PKLE)

TC_EOS k = 3 (or possibly k = 4, KBSM, LINC)
GR1.x/y k = 3
GR100.x k = 3 (or k = 5 for PKLE, TMPL, OVTN)
GR50.x  k = 3 (or k = 5 for PKLE, TMPL, OVTN)
