---
title: "map all metadata"
author: "Alice MacQueen"
date: "7/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(maps)
library(ggmap)
usa <- map_data("usa")
source("~/Github/Functions_ggplot-theme-adjustments_2018-01-03.R")
workingdir <- file.path("~", "Github", "pvdiv-phenology-gxe")
subpops <- read_rds(file.path(workingdir, "data", "subpop_color_coding.rds"))
metadata <- read_rds(file.path(workingdir, "data", "metadata.rds"))
```
Metadata sent to David Lowry 2020-07-31
```{r}
metadata %>%
  dplyr::select(PLANT_ID:GENETIC_SUBPOP_KINSHIP, SUBPOP, ECOTYPE_NNET, PLOIDY:PLANTED_2018) %>%
  mutate(LONGITUDE = -LONGITUDE) %>%
  write_csv(., "pvdiv_gwas_metadata.csv")
```


#

```{r cars}
library(ggrepel)

metaplot <- metadata %>%
  filter(!is.na(LATITUDE)) %>%
  mutate(LONGITUDE = -LONGITUDE)
metaplot$ECOTYPE_NNET <- factor(metaplot$ECOTYPE_NNET, levels = c("Coastal", "Lowland", "Upland", "Unknown"))
siteplot <- sites %>%
  filter(!(SITE %in% c("FRMI", "OVTN")))

ggplot() + 
  geom_polygon(data = usa, aes(x=long, y = lat, group = group), 
               fill = "white", color = "black") +
  coord_quickmap(xlim = c(-105, -66), ylim = c(25, 50)) +
  geom_jitter(data = metaplot, aes(x = LONGITUDE, y = LATITUDE, 
                                   color = SUBPOP, shape = ECOTYPE_NNET),
              width = 0.45, height = 0.45) + 
  geom_point(data = siteplot, aes(x = Longitude, y = Latitude), shape = 21, size = 4, stroke = 1.5, fill = "white") +
  geom_point(data = siteplot, aes(x = Longitude, y = Latitude), shape = 4, size = 3, stroke = 1.5) +
  geom_label_repel(data = siteplot, aes(x = Longitude, y = Latitude, label = manu_site), alpha = 0.7) +
  labs(x = "Longitude", y = "Latitude") + 
  theme(legend.position = "right") +
  #scale_color_viridis(discrete = TRUE) +
  scale_shape_manual(values = c(0, 6, 1, 4, 5)) +
  #scale_fill_manual(values = c("#280B54FF","#FAC127FF", "#D44842FF", "white")) +
  scale_color_manual(values = c(rep("grey", 1), "#090906","#6E91CB", "#F47F72", "#442C83", "#280B54FF","#FAC127FF", "#D44842FF", "white")) 
  #scale_alpha_manual(values = c(0.7, 0.7, 0.7, 0.7), guide = FALSE)
save_plot(filename = "../manuscript/plots/Map_all_subpops_and_Ecotypes.png", plot = last_plot(), base_height = 4)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
